(TeX-add-style-hook "chapter1"
 (lambda ()
    (LaTeX-add-index-entries
     "解决问题"
     "编程语言"
     "语言!编程"
     "移植性"
     "高级语言"
     "低级语言"
     "语言!高级"
     "语言!低级"
     "complie"
     "interpret"
     "源码"
     "目标"
     "可执行代码"
     "交互模式"
     "脚本模式"
     "提示符"
     "脚本"
     "测试!交互模式"
     "程序"
     "算法"
     "调试"
     "臭虫"
     "语法错误"
     "错误!语法"
     "错误信息"
     "syntax 语法"
     "parentheses!matching  括号!匹配"
     "cummings, e. e. 康明思"
     "runtime error 运行时错误"
     "error!runtime 错误!运行时"
     "exception 异常"
     "safe language 安全语言"
     "language!safe 语言!安全"
     "semantics 语义"
     "semantics errors 语义错误"
     "error!semantic 错误!语义"
     "error message 错误信息"
     "experimental debugging 实验性的调试"
     "debugging!experimental 调试!实验"
     "Holems, Sherlock"
     "Doyle, Arthur Conan"
     "Linux"
     "formal language 正式语言"
     "natural language 自然语言"
     "language!formal 语言!正式"
     "language!natural 语言!自然"
     "token 标记"
     "structure 结构"
     "parse 句法分析"
     "ambiguity 二义性"
     "redundancy 冗余性"
     "literalness 无修饰性"
     "poetry 诗歌"
     "prose 散文"
     "Hello, World"
     "Python 3.0"
     "quotation mark 引号"
     "print statement print 语句"
     "statement!print 语句!打印"
     "debugging 调试"
     "debugging!emotional response 调试!情绪反应"
     "emotional debugging 情绪调试"
     "compile 编译"
     "object code 目标代码"
     "prompt 提示符"
     "script 脚本"
     "interactive mode 交互模式"
     "script mode 脚本模式"
     "program 程序"
     "algorithm"
     "bug"
     "syntax error"
     "semantics error 语义错误"
     "documentation 文档"
     "python.org"
     "help utility 帮助工具"
     "caculator 计算器"
     "running pace 跑步速度")
    (LaTeX-add-labels
     "runtime 运行时"
     "hello")))

